### ISSUE TITLE
sideEffect在类内打印和类外打印不一致

### ISSUE THREAD

**Issue by yingYYDoL** [XZ-X/2020SE1-FAQ#3]
对于测试样例 <testSideEffect> 出现错误。
我的代码流程如下：若有-s则改变sideEffect为true，getSideEffectFlag函数返回sideEffect。
问题：在main函数内打印测试，发现确实为true。设置断点调试，发现main函数返回后，在TEST的 <runMain> 函数，sideEffect返回是false。
我尝试过的方法：把main函数的返回值从void改成CommandLineUtil，顺利通过本地测试，云端测试失败，失败信息为：
============================================================
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at edu.nju.CommandLineUtilTest.testSideEffect(CommandLineUtilTest.java:37)
============================================================

**Comment by XZ-X** [comment]
经过检查，这应该不是测试用例的错误。再仔细检查一下你的代码？
